export const AP_TG_DISTRICTS = [
  "Adilabad",
  "Alluri Sitharama Raju",
  "Anakapalli",
  "Anantapur",
  "Annamayya",
  "Asifabad",
  "Bapatla",
  "Bhadradri Kothagudem",
  "Chittoor",
  "Dr. B.R. Ambedkar Konaseema",
  "East Godavari",
  "Eluru",
  "Guntur",
  "Hanamkonda",
  "Hyderabad",
  "Jagtial",
  "Jangaon",
  "Jayashankar Bhupalpally",
  "Jogulamba Gadwal",
  "Kakinada",
  "Kamareddy",
  "Karimnagar",
  "Khammam",
  "Krishna",
  "Kumuram Bheem Asifabad",
  "Kurnool",
  "Mahabubabad",
  "Mahabubnagar",
  "Mancherial",
  "Medak",
  "Medchal-Malkajgiri",
  "Mulugu",
  "NTR",
  "Nagarkurnool",
  "Nalgonda",
  "Nandyal",
  "Narayanpet",
  "Nellore",
  "Nirmal",
  "Nizamabad",
  "Palnadu",
  "Parvathipuram Manyam",
  "Peddapalli",
  "Prakasam",
  "Rajanna Sircilla",
  "Rangareddy",
  "Sangareddy",
  "Siddipet",
  "Srikakulam",
  "Sri Potti Sriramulu Nellore",
  "Sri Sathya Sai",
  "Suryapet",
  "Tirupati",
  "Visakhapatnam",
  "Vikarabad",
  "Vizianagaram",
  "Wanaparthy",
  "Warangal",
  "West Godavari",
  "Yadadri Bhuvanagiri",
  "YSR Kadapa",
] as const;

export const AP_TG_CITIES = [
  "Adilabad",
  "Amadalavalasa",
  "Amalapuram",
  "Amaravati",
  "Anakapalle",
  "Anantapur",
  "Armur",
  "Atmakur",
  "Bapatla",
  "Bhadrachalam",
  "Bhainsa",
  "Bheemunipatnam",
  "Bhongir",
  "Bodhan",
  "Chilakaluripet",
  "Chirala",
  "Chittoor",
  "Dharmavaram",
  "Dhone",
  "Eluru",
  "Gadwal",
  "Gajuwaka",
  "Gooty",
  "Gudivada",
  "Gudur",
  "Guntakal",
  "Guntur",
  "Hanamkonda",
  "Hindupur",
  "Hyderabad",
  "Jaggayyapeta",
  "Jagtial",
  "Jangaon",
  "Kadapa",
  "Kakinada",
  "Kamareddy",
  "Karimnagar",
  "Kavali",
  "Khammam",
  "Kodad",
  "Kothagudem",
  "Kuppam",
  "Kurnool",
  "Macherla",
  "Machilipatnam",
  "Madanapalle",
  "Mahabubabad",
  "Mahabubnagar",
  "Mangalagiri",
  "Mancherial",
  "Mandapeta",
  "Markapur",
  "Medak",
  "Miryalaguda",
  "Nagari",
  "Nalgonda",
  "Nandyal",
  "Narasapuram",
  "Narasaraopet",
  "Narsipatnam",
  "Nellore",
  "Nidadavole",
  "Nirmal",
  "Nizamabad",
  "Nuzvid",
  "Ongole",
  "Palakollu",
  "Palasa",
  "Parvathipuram",
  "Peddapalli",
  "Piduguralla",
  "Proddatur",
  "Punganur",
  "Puttur",
  "Rajahmundry",
  "Rajam",
  "Ramagundam",
  "Repalle",
  "Sangareddy",
  "Sattenapalle",
  "Siddipet",
  "Sirsilla",
  "Srikakulam",
  "Srikalahasti",
  "Suryapet",
  "Tadepalligudem",
  "Tadipatri",
  "Tandur",
  "Tanuku",
  "Tenali",
  "Tirupati",
  "Vemulawada",
  "Vijayawada",
  "Vinukonda",
  "Visakhapatnam",
  "Vizianagaram",
  "Wanaparthy",
  "Warangal",
  "Yelamanchili",
  "Yemmiganur",
] as const;

export const OPEN_PLOT_AMENITIES = [
  "24x7 Security",
  "Avenue Plantation",
  "Bank Loan Available",
  "Black Top Roads",
  "Boundary Fencing",
  "Bus Stop Nearby",
  "CC Roads",
  "Children's Park",
  "City Center Access",
  "Clubhouse",
  "Compound Wall",
  "Curb Stones",
  "Cycle Track",
  "Daily Needs Store Nearby",
  "Drainage",
  "DTCP Approved",
  "Electricity",
  "Entrance Arch",
  "Footpaths",
  "Gated Community",
  "Grand Entrance",
  "Gym",
  "HMDA Approved",
  "Highway Facing",
  "Hospital Nearby",
  "LED Street Lights",
  "Loan Facility",
  "Overhead Water Tank",
  "Parks",
  "Paved Internal Roads",
  "Petrol Pump Nearby",
  "Play Area",
  "Rainwater Harvesting",
  "Residential Zone",
  "School Nearby",
  "Security Cabin",
  "Sewer Line",
  "Temple Nearby",
  "Underground Cabling",
  "Underground Drainage",
  "Vastu Compliant",
  "Water Connection",
  "Water Pipeline",
] as const;
